### ISSUE TITLE
Unable to Override Breadcrumbs Component

### ISSUE THREAD

**Issue by kylekanderson** [wireui/breadcrumbs#2]
The package is setup to publish the `breadcrumbs.blade.php` view component to `/resources/views/vendor/wireui/breadcrumbs/breadcrumbs.blade.php`. However, the package does not load an overridden view component from this directory.

It appears that you are able to override the view component by creating a `breadcrumbs.blade.php` file inside of the `/resources/views/vendor/wireui.breadcrumbs` directory instead.

I believe an update is needed to how views are loaded in the `BreadcrumbsServiceProvider.php` file.

**Comment by PH7-Jack** [comment]
@kylekanderson Hi, a fix was released. Thanks for reporting.
